# Generated by Django 3.2.8 on 2022-10-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotrackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Select_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('header1', models.CharField(db_column='header1', max_length=50, verbose_name='Header1')),
                ('header2', models.CharField(db_column='header2', max_length=50, verbose_name='Header2')),
                ('header3', models.CharField(db_column='header3', max_length=50, null=True, verbose_name='Header3')),
                ('header4', models.CharField(db_column='header4', max_length=50, null=True, verbose_name='Header4')),
                ('header5', models.CharField(db_column='header5', max_length=50, verbose_name='Header5')),
                ('header6', models.CharField(db_column='header6', max_length=50, verbose_name='Header6')),
            ],
            options={
                'db_table': 'Select_data',
            },
        ),
    ]
