# Generated by Django 3.2.8 on 2022-10-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotrackapp', '0002_select_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='select_data',
            name='no',
            field=models.CharField(db_column='no', max_length=50, null=True, verbose_name='No'),
        ),
        migrations.AlterField(
            model_name='select_data',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
