# Generated by Django 3.2.8 on 2022-10-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infotrackapp', '0003_auto_20221003_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='select_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
